# Generated by Django 5.2.4 on 2026-05-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=124, verbose_name='Имя')),
                ('surname', models.CharField(max_length=124, verbose_name='Фамилия')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='Аватар')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('about', models.TextField(blank=True, max_length=256, verbose_name='О себе')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('favorites', models.ManyToManyField(blank=True, related_name='interested_users', to='projects.project', verbose_name='Избранное')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
